---
- name: Verificar atualizações no sistema
  hosts: all
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Atualizar lista de pacotes
      apt:
        update_cache: yes

    - name: Verificar atualizações disponíveis
      apt:
        upgrade: yes
      register: result

    - name: Exibir atualizações disponíveis
      debug:
        var: result.stdout_lines
