---
- name: Atualizar e fazer upgrade dos pacotes
  hosts: all
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Atualizar lista de pacotes
      apt:
        update_cache: yes

    - name: Fazer upgrade dos pacotes
      apt:
        upgrade: yes
